server:
  port: 7020
spring:
  cloud:
    config:
      server:
        git:
          uri: http://localhost:8081/root/config-server.git
          search-paths: /**
          username: root
          password: admin123
    bus:
      refresh:
        enabled: true
  application:
    name: Config-Server
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

